[telegram]
server = "https://api.telegram.org/bot"
bot_token = "123456789:ABCDEFGHIJKLMNOPQRSTUVWXYZ091234567"

# Proxy settings are passed to requests.Session
[proxy]
https = "socks5h://127.0.0.1:1080"

[doorbell]
spec = "doorbell:OOK_PWM:1000:1400:44400:1000000"
payload = [42, 219, 93] # 0x2A, 0xDB, 0x5D (because toml recently added hex support that isn't adopted anywher yet?!)

jokes = [
    "Hey, did someone order pizza?",
    "Knock knock. Who's there? I don't know, i'm just a doorbell!",
    "Looks like a delivery of fresh memes at the door",
    "Some has startled door and is now alarmed",
]

[[doorbell.chats]]
chat_id = 123456789
chat_type = 'private'
